// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// predict_lp_cpp
NumericMatrix predict_lp_cpp(IntegerMatrix codes, IntegerVector ls, List stagemap, List probs, int class_pos);
RcppExport SEXP _stagedtrees_predict_lp_cpp(SEXP codesSEXP, SEXP lsSEXP, SEXP stagemapSEXP, SEXP probsSEXP, SEXP class_posSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type codes(codesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ls(lsSEXP);
    Rcpp::traits::input_parameter< List >::type stagemap(stagemapSEXP);
    Rcpp::traits::input_parameter< List >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< int >::type class_pos(class_posSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_lp_cpp(codes, ls, stagemap, probs, class_pos));
    return rcpp_result_gen;
END_RCPP
}
// path_lp_cpp
NumericVector path_lp_cpp(IntegerMatrix codes, IntegerVector ls, List stagemap, List probs);
RcppExport SEXP _stagedtrees_path_lp_cpp(SEXP codesSEXP, SEXP lsSEXP, SEXP stagemapSEXP, SEXP probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type codes(codesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ls(lsSEXP);
    Rcpp::traits::input_parameter< List >::type stagemap(stagemapSEXP);
    Rcpp::traits::input_parameter< List >::type probs(probsSEXP);
    rcpp_result_gen = Rcpp::wrap(path_lp_cpp(codes, ls, stagemap, probs));
    return rcpp_result_gen;
END_RCPP
}
// best_merge_cpp
NumericVector best_merge_cpp(NumericMatrix pm, NumericVector nvec, double lambda, int k);
RcppExport SEXP _stagedtrees_best_merge_cpp(SEXP pmSEXP, SEXP nvecSEXP, SEXP lambdaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pm(pmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(best_merge_cpp(pm, nvec, lambda, k));
    return rcpp_result_gen;
END_RCPP
}
// best_move_cpp
NumericMatrix best_move_cpp(NumericMatrix ct, IntegerVector asg, int nstage, double lambda);
RcppExport SEXP _stagedtrees_best_move_cpp(SEXP ctSEXP, SEXP asgSEXP, SEXP nstageSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ct(ctSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type asg(asgSEXP);
    Rcpp::traits::input_parameter< int >::type nstage(nstageSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(best_move_cpp(ct, asg, nstage, lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stagedtrees_predict_lp_cpp", (DL_FUNC) &_stagedtrees_predict_lp_cpp, 5},
    {"_stagedtrees_path_lp_cpp", (DL_FUNC) &_stagedtrees_path_lp_cpp, 4},
    {"_stagedtrees_best_merge_cpp", (DL_FUNC) &_stagedtrees_best_merge_cpp, 4},
    {"_stagedtrees_best_move_cpp", (DL_FUNC) &_stagedtrees_best_move_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_stagedtrees(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
