# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predict_lp_cpp <- function(codes, ls, stagemap, probs, class_pos) {
    .Call(`_stagedtrees_predict_lp_cpp`, codes, ls, stagemap, probs, class_pos)
}

#' Best pairwise stage merge, by log-likelihood
#'
#' @param pm stage-by-level matrix of probabilities.
#' @param nvec per-stage sample sizes; non-finite entries are treated as 1,
#'   as \code{join_ll_delta} does.
#' @param lambda smoothing parameter.
#' @param k number of levels of the variable.
#' @return numeric vector of length three: the 1-based indices of the two
#'   stages to merge, and the resulting change in log-likelihood. Every
#'   pairwise merge changes the degrees of freedom by the same amount, so a
#'   single representative is returned.
#' @keywords internal
best_merge_cpp <- function(pm, nvec, lambda, k) {
    .Call(`_stagedtrees_best_merge_cpp`, pm, nvec, lambda, k)
}

best_move_cpp <- function(ct, asg, nstage, lambda) {
    .Call(`_stagedtrees_best_move_cpp`, ct, asg, nstage, lambda)
}

